k8sgpt-ai/community

- interested-parties.md
Closes # 
I added myself to interested-parties
> feat: add matthisholleville to interested-parties

- community-membership.md
Closes # 
* Adds definition of membership in the respective github team
> doc: refined contributor ladder

- .github/ISSUE_TEMPLATE/membership_request.yaml
Closes # 
* Adds a form for membership requests
* Preview: https://github.com/thschue/k8sgpt-community/issues/new/choose
> chore: add membership request form

- .github/CODEOWNERS
- .github/settings.yml
> chore: add managed settings for repo

- .github/ISSUE_TEMPLATE/adoption_use_cases.yaml
- ADOPTERS.md
* Add form to gather Adoption Information
* Add ADOPTERS file
> chore: add adopter feedback form and file

- interested-parties.md
> feat: add matthisholleville to intersted-parties

- interested-parties.md
Closes # 
Add myself into interested-party
> chore: add panpan0000 to interested-parties 

- interested-parties.md
Closes # 
Hi, guys. I'm Aisuko. Student of RMIT. My major is in Cloud computing and it is (a little bit)related to the AI domain. Glad to see you guys combine these two topics together already. I'd like to do contributions to the projects. I was a maintainer for the GNU Hurd project and `Meshery` communities for many years, so I believe I can do a lot of things here.
> Add myself to the interested individual table

- interested-parties.md
> feat: add rakshitgondwal to interested-parties.md

- interested-parties.md
> docs: update interested-parties.md

- CHARTER.md
> fix: update CHARTER.md License Agreement

- interested-parties.md
Added my name to the list of interested parties for the project!
> Add: Name as an Interested Party

- README.md
Closes #41
This PR fixes the broken link to point to correct docs to know about Interested Parties.
> Update README.md to fix the broken link

- README.md
- interested-parties.md
👋 
I'm Camilo Giraldo and would like to get involved with the project.
- Added myself to interested parties.
- Removed **_Interested Parties_** section in Readme as it seemed to be a duplicate of **Getting started** and a broken link to Notion.
- Added link /k8sgpt/CONTRIBUTING.md into **_Contributing_** section.
> docs: update readme and interested parties

- ADOPTERS.md
> docs: added Nethopper to Adopters page

- README.md
Removed current links and added slack link
> update office hours section to remove current links

- README.md
> corrected the contributing.md guide link

- interested-parties.md
- Fixed markdown table formatting :)
Closes #
> feat: add rudrakshkarpe to update interested-parties.md

- MAINTAINERS.md
- subprojects.md
* Removes @thschue as a maintainer
> chore: update MAINTAINERS

- MAINTAINERS.md
> chore: add maintainer

- interested-parties.md
Closes # 
add kay to update interested-parties.md
> feat: add kay to update interested-parties.md
